export const CUSTOMERS_REQUEST = 'CUSTOMERS_REQUEST';
export const CUSTOMERS_RECEIVED = 'CUSTOMERS_RECEIVED';
export const CUSTOMERS_ERROR = 'CUSTOMERS_ERROR';


export const ORDERS_REQUEST = 'ORDERS_REQUEST';
export const ORDERS_RECEIVED = 'ORDERS_RECEIVED';
export const ORDERS_ERROR = 'ORDERS_ERROR';
